version: "3"

volumes:
  jena_data:


services:
  fuseki:
    image: secoresearch/fuseki:4.9.0
    restart: on-failure
    ports:
      - "3030:3030"
    environment:
      - JAVA_OPTIONS=-Xmx10g -Xms10g -DentityExpansionLimit=0
      - ADMIN_PASSWORD=admin
      - ENABLE_DATA_WRITE=true
      - ENABLE_UPDATE=true
      - ENABLE_UPLOAD=true
      - QUERY_TIMEOUT=60000
    volumes:
      - jena_data:/fuseki-base
      - ./fuseki/index.html:/jena-fuseki/webapp/index.html
      - ./fuseki/shiro.ini:/jena-fuseki/shiro.ini
    stop_grace_period: 10s
    healthcheck:
      test:
        - "CMD-SHELL"
        - "wget -qO /dev/null http://localhost:3030/$$/ping || exit 1"
      interval: 10s
      timeout: 5s
      retries: 3
    networks:
      - datastack_net
  sparklis:
    expose:
      - 8080
    image: sferre/sparklis:latest
    networks:
      - datastack_net
    restart: unless-stopped
networks:
  datastack_net:
