version: "3"

volumes:
  jena_data:


services:
  fuseki:
    image: stain/jena-fuseki
    restart: unless-stopped
    ports:
      - "3030:3030"
    environment:
      - JVM_ARGS=-Xmx10g -DentityExpansionLimit=0
    volumes:
      - jena_data:/fuseki
      - ./fuseki/config.ttl:/fuseki/config.ttl
      - ./fuseki/jetty.xml:/fuseki/jetty.xml
    command: [ "/jena-fuseki/fuseki-server", "--jetty-config=/fuseki/jetty.xml" ]
    stop_grace_period: 10s
    healthcheck:
      test:
        - "CMD-SHELL"
        - "wget -qO /dev/null http://localhost:3030/$$/ping"
        - "test ! -f /system/tdb.lock"
      interval: 10s
      timeout: 5s
      retries: 3
    networks:
      - datastack_net
  sparklis:
    expose:
      - 8080
    image: sferre/sparklis:latest
    networks:
      - datastack_net
networks:
  datastack_net:
